"""new table careers

Revision ID: 2b7a06a94761
Revises: fc19806547be
Create Date: 2024-08-11 15:12:22.919840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b7a06a94761"
down_revision: Union[str, None] = "fc19806547be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=400), nullable=False),
        sa.Column("fullname", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="reformify",
    )
    op.create_index(
        op.f("ix_reformify_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="reformify",
    )
    op.create_table(
        "careers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("company", sa.String(length=100), nullable=False),
        sa.Column("company_location", sa.String(length=100), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("job_location", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("company_description", sa.String(length=400), nullable=False),
        sa.Column("description", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["reformify.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="reformify",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("careers", schema="reformify")
    op.drop_index(
        op.f("ix_reformify_users_email"), table_name="users", schema="reformify"
    )
    op.drop_table("users", schema="reformify")
    # ### end Alembic commands ###
