"""make careers.end_date nullable

Revision ID: ccada3646d48
Revises: 2b7a06a94761
Create Date: 2024-08-11 16:49:40.171230

"""

from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ccada3646d48"
down_revision: Union[str, None] = "2b7a06a94761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("careers", "end_date", schema="reformify", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("careers", schema="reformify")
    op.drop_index(
        op.f("ix_reformify_users_email"), table_name="users", schema="reformify"
    )
    op.drop_table("users", schema="reformify")
    # ### end Alembic commands ###
