"""new relations and columns in users and profile_sections

Revision ID: fc19806547be
Revises: a142f1b36112
Create Date: 2024-08-10 16:38:34.880499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc19806547be"
down_revision: Union[str, None] = "a142f1b36112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="reformify",
    )
    op.create_index(
        op.f("ix_reformify_user_profiles_email"),
        "user_profiles",
        ["email"],
        unique=True,
        schema="reformify",
    )
    op.create_index(
        op.f("ix_reformify_user_profiles_id"),
        "user_profiles",
        ["id"],
        unique=True,
        schema="reformify",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=400), nullable=False),
        sa.Column("fullname", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="reformify",
    )
    op.create_index(
        op.f("ix_reformify_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="reformify",
    )
    op.create_table(
        "profile_sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["reformify.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="reformify",
    )
    op.create_table(
        "user_careers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["reformify.user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="reformify",
    )
    op.create_index(
        op.f("ix_reformify_user_careers_id"),
        "user_careers",
        ["id"],
        unique=True,
        schema="reformify",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reformify_user_careers_id"),
        table_name="user_careers",
        schema="reformify",
    )
    op.drop_table("user_careers", schema="reformify")
    op.drop_table("profile_sections", schema="reformify")
    op.drop_index(
        op.f("ix_reformify_users_email"), table_name="users", schema="reformify"
    )
    op.drop_table("users", schema="reformify")
    op.drop_index(
        op.f("ix_reformify_user_profiles_id"),
        table_name="user_profiles",
        schema="reformify",
    )
    op.drop_index(
        op.f("ix_reformify_user_profiles_email"),
        table_name="user_profiles",
        schema="reformify",
    )
    op.drop_table("user_profiles", schema="reformify")
    # ### end Alembic commands ###
